spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb+srv://Psortnik:<Piotr2013>@chess-tpa-notification.gtl4g4g.mongodb.net/chess-tpa-notification


server:
  port: 0


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus