spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
#Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.tpa.gameservice.event.LogEvent



server:
  port: 8083

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.io.IOException

  instances:
    user-service:
      baseConfig: default

#resilience4j.timelimiter:
#  configs:
#    default:
#      timeoutDuration: 3s
#  instances:
#    user-service:
#      baseConfig: default
#
#resilience4j.retry:
#  configs:
#    default:
#      max-attempts: 3
#      wait-duration: 5s
#  instances:
#    user-service:
#      baseConfig: default
