spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: queue-service
          uri: lb://queue-service
          predicates:
            - Path=/api/queue/**
        - id: accesscontrol-service
          uri: lb://accesscontrol-service
          predicates:
            - Path=/api/auth/**
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/api/game/**
        - id: websocket-service
          uri: lb://websocket-service
          predicates:
            - Path=/stomp/**
        - id: analysis-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/analysis/**
            - Method=GET, POST, OPTIONS
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    root: debug
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
