spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservice-realm
  cloud:
    gateway:
      routes[0]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[1]:
        id: user-service
        uri: http://localhost:8081
        predicates[0]: Path=/api/user
