spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/chess-tpa
  cloud:
    gateway:
      routes[0]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[1]:
        id: user-service
        uri: http://localhost:8081
        predicates[0]: Path=/api/user
      routes[2]:
        id: accesscontrol-service
        uri: http://localhost:8082
        predicates[0]: Path=/api/auth/**