eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@host.docker.internal:8761/eureka

spring:
  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: queue-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


management:
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411