server:
  port: 8082
spring:
  application:
    name: accesscontrol-service
#keycloak
keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: http://localhost:8181
  ssl-required: external
  resource: ${KEYCLOAK_RESOURCE}
  credentials:
    secret: ${KEYCLOAK_SECRET}
  use-resource-role-mappings: true
  bearer-only: true

management:
  tracing:
    sampling:
      probability: 1.0

management.health.circuitbreakers.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always



resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.io.IOException

  instances:
    user-service:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 3s
  instances:
    user-service:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 5s
  instances:
    user-service:
      baseConfig: default