server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@host.docker.internal:8761/eureka

keycloak:
  realm: Chess-TPA
  auth-server-url: http://localhost:8181
  ssl-required: external
  resource: chess-tpa
  credentials:
    secret: OCBVjq63DZ5HInaJ1bRKSM9X09mNWm4I
  use-resource-role-mappings: true
  bearer-only: true


management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - java.io.IOException

  instances:
    user-service:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 3s
  instances:
    user-service:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 5s
  instances:
    user-service:
      baseConfig: default
