#keycloak
keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: http://localhost:8181
  ssl-required: external
  resource: ${KEYCLOAK_RESOURCE}
  credentials:
    secret: ${KEYCLOAK_SECRET}
  use-resource-role-mappings: true
  bearer-only: true

server:
  port: 8082


spring:
  application:
      name: accesscontrol-service