spring:
  application:
    name: chessengine-service
server:
  port: 8084

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus


